### ISSUE TITLE
Subpath

### ISSUE THREAD

**Issue by voroyam** [univention/univention-owncloud-saml#4]
Hello,

could someone explain the purpose of this line?

`/root/owncloud/` was never a directory that existed.

In the older app the dir was `/var/lib/owncloud/` and now it's `/var/lib/univention-appscenter/apps/owncloud`

I think this file belongs in the apache config. But I might be wrong.

https://github.com/univention/univention-owncloud-saml/blob/8968c234a02de5de6d4cd29e3df16e6dd9ab3a5e/40univention-owncloud-saml.inst#L70

**Comment by spaceone** [comment]
Well, from my remembering the path was once `/root/owncloud/`. If the path changed, a PR with the correct new path is welcome! And if the file contents changed we should rebase the file.

**Comment by voroyam** [comment]
What is the purpose of the file subpath.conf?

I doubt that the file has to be in the ownCloud directory

**Comment by spaceone** [comment]
As far as I remember it causes that the path in the UCR variable `owncloud/saml/path` is configurable, which is the entry point to the owncloud shiboleth service provider.

**Comment by voroyam** [comment]
so the path is usually `/owncloud/oc-shib`?

**Comment by spaceone** [comment]
Yes, or at least it has been this path in the beginning. I think I just got that path from the manual in https://doc.owncloud.org/server/10.0/admin_manual/enterprise/user_management/user_auth_shibboleth.html?highlight=oc-shib back then.

**Comment by voroyam** [comment]
So if I got this right, you only need this file if you want to customize the path to the shibboleth login, but if you want to let it as is, you don't need it?

**Comment by spaceone** [comment]
See also Issue #5

**Comment by spaceone** [comment]
and Pull Request #7

**Comment by voroyam** [comment]
thanks @spaceone this issue can be closed.
