### ISSUE TITLE
Need new app release to include libshib8

### ISSUE THREAD

**Issue by voroyam** [univention/univention-owncloud-saml#5]
Need new app release to include libshib8

**Comment by voroyam** [comment]
@spaceone

**Comment by spaceone** [comment]
@voroyam Can you provide a pull request with the necessary changes?

**Comment by voroyam** [comment]
This one already got merged, but what is missing is the release.

https://github.com/univention/univention-owncloud-saml/pull/3

@spaceone

**Comment by voroyam** [comment]
Can you also explain the #FIXME chomod in the script?

Maybe with this release we can fix this.

**Comment by voroyam** [comment]
https://github.com/univention/univention-owncloud-saml/blob/master/40univention-owncloud-saml.inst#L75

**Comment by spaceone** [comment]
This is the private key, which should not be readable by any user than root or owncloud or whatever uses it.

**Comment by voroyam** [comment]
We need also fix the docker cp command. Because of it the script fails.

**Comment by voroyam** [comment]
https://github.com/univention/univention-owncloud-saml/blob/master/40univention-owncloud-saml.inst#L70

**Comment by voroyam** [comment]
the /root/owncloud/ folder is not there. We either need a target, or just copy it to /root/

**Comment by enbrnz** [comment]
> Can you also explain the #FIXME chomod in the script?
> 
> Maybe with this release we can fix this.

> This is the private key, which should not be readable by any user than root or owncloud or whatever uses it.

It needs to be owned by `_shibd` uid: 102  gid: 105
I think after copying at has some weird ownership uid: 2020 and gid: 5005

And yes `chmod go-rwx`

**Comment by enbrnz** [comment]
> the /root/owncloud/ folder is not there. We either need a target, or just copy it to /root/

When we tried using the package today I think it failed at exactly that step, because the folder `/root/owncloud/` doesn't exist:
https://github.com/univention/univention-owncloud-saml/blob/master/40univention-owncloud-saml.inst#L70

Once I did the steps after that, the rest seemed to worked fine (wasn't able to test everything yet).

**Comment by spaceone** [comment]
Thanks for the pull request! Is there anything still open? The `/root/owncloud`  path issue?

**Comment by voroyam** [comment]
Yes

**Comment by spaceone** [comment]
Released as: https://github.com/univention/univention-owncloud-saml/releases/tag/1.0.0-5
